typography_spectrum: 0.4652908386408103
content_rating:
  adult: false
color:
  lightness: 0.02403338400554834
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  saturation: 0.7896113398362247
  brandStrength: 0.6840322825944255
  rhythmicContrast: 0.5397919747989515
github: true
opengraph:
  type: ''
layout_spectrum: 0.5032699069510777
analytics:
  google: UA-98409841-1
author:
  name: KaraokeNJ.com
  url: 'Http://www.KaraokeNJ.com'
  email: KaraokeNewJersey@Gmail.com
name: KaraokeNJ.com
navigation:
  - name: Facebook Fan Page!!
    url: 'https://www.facebook.com/Karaoke-New-Jersey-217284738765871/?ref=br_rs'
    type: external
  - name: Facebook Karaoke Group In New Jersey
    url: 'https://www.facebook.com/groups/SingKaraokeNJ/'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: KaraokeNJ.com
content: []
coverPrefs:
  filter: false
description: 'The Best of the Best of New Jersey''s Karaoke Nights!! '
purpose:
  - type: external
    url: 'https://www.facebook.com/Karaoke-New-Jersey-217284738765871/?ref=br_rs'
    label: FACBOOK FAN PAGE /Karaoke-New-Jersey
  - type: external
    url: 'https://www.facebook.com/groups/SingKaraokeNJ/'
    label: FACEBOOK Groups/SingKaraokeNJ/
