name: KaraokeNJ.com
analytics: {}
github: true
description: 'The Best of the Best of New Jersey''s Karaoke Nights!! '
author:
  name: KaraokeNJ.com
  url: 'Http://www.KaraokeNJ.com'
  email: KaraokeNewJersey@Gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
layout_spectrum: 0.5032699069510777
color:
  lightness: 0.02403338400554834
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  saturation: 0.7896113398362247
  brandStrength: 0.6840322825944255
  rhythmicContrast: 0.5397919747989515
content_rating:
  adult: false
typography_spectrum: 0.4652908386408103
opengraph:
  type: kreilky1
title: KaraokeNJ.com
coverPrefs:
  filter: false
purpose:
  - type: external
    url: 'https://www.facebook.com/Karaoke-New-Jersey-217284738765871/?ref=br_rs'
    label: FACBOOK FAN PAGE /Karaoke-New-Jersey
  - type: external
    url: 'https://www.facebook.com/groups/SingKaraokeNJ/'
    label: FACEBOOK Groups/SingKaraokeNJ/
