layout_spectrum: 0.7103973856328589
typography_spectrum: 0.7508362511905962
color:
  lightness: 0.49307647964575946
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  saturation: 0.32633477283143764
  brandStrength: 0.9732285999732626
  rhythmicContrast: 0.7005552492215122
coverPrefs:
  filter: false
name: karaokenj
analytics: {}
github: true
description: >-
  The Best of the Best of New Jersey's Karaoke!!  New Jersey's Newest Karaoke
  Hotspot for Karaoke Singing Videos, Pictures, Karaoke Location Hosts, Dates
  and Times! Visit us at http://www.KaraokeNJ.com.  Follow is on Facebook at
  Facebook.com/KaraokeNewJersey --- Twitter @SingKaraokeNJ  --- Instagram
  @KaraokeNJ. --- YouTube Channel @KaraokeNewJersey. --- Email Us @
  KaraokeNewJersey@Gmail.com 
author:
  name: Keith Reily
  url: 'Http://www.PlayThruInc.com'
  email: Keith@KeithReilly.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph:
  type: kreilky1
title: KaraokeNJ.com
